import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "./globals.css";
import { Tabs } from "@/components/Tabs";
import { Toaster } from "sonner";
import {NavigationBar} from "@/components/NavigationBar";

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
        <body className="bg-black text-white">
        <Toaster position="top-center" />
        <main className="">
            <NavigationBar/>
            <Tabs />
            <div className="mt-6">{children}</div>
        </main>
        </body>
        </html>
    );
}

